-- Clean all tables
DROP TABLE IF EXISTS topic_foundation_requirements CASCADE;
DROP TABLE IF EXISTS foundation_mastery CASCADE;
DROP TABLE IF EXISTS foundation_dependencies CASCADE;
DROP TABLE IF EXISTS foundations CASCADE;
DROP TABLE IF EXISTS parent_access_sessions CASCADE;
DROP TABLE IF EXISTS document_metadata CASCADE;
DROP TABLE IF EXISTS ai_usage_logs CASCADE;
DROP TABLE IF EXISTS progress CASCADE;
DROP TABLE IF EXISTS review_schedules CASCADE;
DROP TABLE IF EXISTS error_patterns CASCADE;
DROP TABLE IF EXISTS task_attempts CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS subtopics CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS users CASCADE;
